[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
actix-web-actors = "4"
actix-ws = "0.3.0"
futures-util = "0.3.31"
tokio = { version = "1", features = ["full"] }
